from .models import AIUseCase, AssuranceResult


def markdown_report(use_case: AIUseCase, result: AssuranceResult) -> str:
    lines = [
        f"# AI Assurance Report — {use_case.name}",
        "",
        f"**Owner:** {use_case.owner}",
        "",
        f"**Decision:** `{result.decision}`",
        "",
        "## Risk summary",
        "",
        f"- Inherent risk: **{result.inherent_risk}/100 ({result.risk_band})**",
        f"- Control coverage: **{result.control_coverage}%**",
        f"- Residual risk: **{result.residual_risk}/100**",
        "",
        "## Decision rationale",
        "",
    ]
    lines.extend(f"- {reason}" for reason in result.reasons)

    lines.extend([
        "",
        "## Control results",
        "",
        "| Control | Domain | Status | Evidence | Score | Critical |",
        "|---|---|---:|---:|---:|---:|",
    ])

    for r in result.control_results:
        lines.append(
            f"| {r.control_id} — {r.title} | {r.domain} | {r.status} | "
            f"{r.evidence_count} | {r.score:.2f} | {'Yes' if r.critical else 'No'} |"
        )

    unresolved = [
        r for r in result.control_results
        if r.status in {"not_implemented", "planned", "partial"}
    ]
    lines.extend(["", "## Unresolved items", ""])
    if unresolved:
        lines.extend(f"- **{r.control_id}** {r.title}: {r.status}" for r in unresolved)
    else:
        lines.append("- None.")

    lines.extend([
        "",
        "## Important limitation",
        "",
        "This report is generated by an educational assurance model. "
        "It is not certification evidence, legal advice, or a substitute for expert review.",
        "",
    ])
    return "\n".join(lines)
